{
 "title": "Bentoml Service dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Adaptive Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(bentoml_runner_adaptive_batch_size_bucket{service_name=\"fraud_detection_service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(bentoml_api_server_request_duration_seconds_bucket{service_name=\"fraud_detection_service\", endpoint=\"/predict\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(bentoml_api_server_request_total{service_name=\"fraud_detection_service\", endpoint=\"/predict\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}